### PR TITLE
update deltafifo usage to match upstream changes

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k this will fix the test that's failing.  how you feel about the fix may be another question.

**Comment by deads2k** [comment]
> @deads2k this will fix the test that's failing. how you feel about the fix may be another question.

wow.

**Comment by bparees** [comment]
@deads2k i take it the fifo change is not going into 3.1

**Comment by deads2k** [comment]
agreed

**Comment by deads2k** [comment]
@soltysh fyi

**Comment by bparees** [comment]
@soltysh you'll still probably need this fix when you go to do the next rebase.

**Comment by deads2k** [comment]
I only closed this because it was a pull against my branch, not because I summarily rejected it.

**Comment by soltysh** [comment]
Yup, will start working on this.

**Pull request closed without merging**
